export const LOCAL_STORAGE_USER_INFO = "LOCAL_STORAGE_USER_INFO";
export const SHOW_MODAL_QUICK_VIEW = "SHOW_MODAL_QUICK_VIEW";
export const LOCAL_STORAGE_CART = "LOCAL_STORAGE_CART";
export const SHOW_MODAL_AUTH = "SHOW_MODAL_AUTH";
export const LOCAL_STORAGE_SHIPPING = "LOCAL_STORAGE_SHIPPING";
